### ISSUE TITLE
VST plugin crashing when i open the UI (Bitwig + Linux)

### ISSUE THREAD

**Issue by g4z** [klangfreund/LUFSMeter#3]
hi

i downloaded the trial version of LUFSmeter plugin (https://www.klangfreund.com/lufsmeter/) and installed the 64bit .so into `$HOME/.vst` folder.

i can successfully load the plugin onto a track, but it crashes everytime when i try to open the UI.

There are no errors reported in the "Plugins with errors" screen from the "Settings > Plugins" menu (which is how Bitwig shows error messages from the plugins).

I wonder several things...

- is anyone successfully running the same set as me? (ie. Linux + Bitwig + LUFSmeter)?
- can i provide any system/debugging info to resolve this problem?

If this is something that can be resolved, feel free to ask me for any info that may help.

Seems like LUFSmeter is one of the few analysis tools available to Linux users (in VST format, at least)!

Cheers :)

--

OS: Ubuntu 18.04.3
DAW: Bitwig 3.0.3

**Comment by klangfreund** [comment]
Hi g4z,

thank you for reporting!

This might be caused by the fact that the LUFS Meter 2.0.0 demo for Linux was compiled for a specific processor architecture.

Can you try the LUFS Meter 2.1.0 beta demo - which has been built for a broader range of processors - and let me know if this issue still occurs?
https://www.klangfreund.com/download/Klangfreund_LUFS_Meter_Demo_2.1.0.tar.gz

May you further give the standalone version of the Multimeter 1.1.0 beta a try? Does it have the same UI issue?
https://www.klangfreund.com/download/Klangfreund_Multimeter_Demo_1.1.0.tar.gz

Cheers,
Samuel

**Comment by g4z** [comment]
All good! 

Both LUFS Meter and Multimeter are working correctly for v2.1.0

I'm gonna check multimeter out a bit more tonight (i hadn't realised that it includes the LUFS functionality!) and expect to purchase it soon.

Nice work sir! Thanks

**Comment by klangfreund** [comment]
Great to hear. Thank you for letting me know! And for your kind words :)

The current beta versions are available from https://www.klangfreund.com/lufsmeter/beta/ and https://www.klangfreund.com/multimeter/beta/
